class RemoveColumnInChages < ActiveRecord::Migration[6.1]
  def change
    remove_column :estimates, :detail1, :integer
    remove_column :estimates, :genre_id1, :integer
    remove_column :estimates, :product1, :string
    remove_column :estimates, :model1, :string
    remove_column :estimates, :amount1, :integer
    remove_column :estimates, :unit_price1, :integer
    remove_column :estimates, :recruit1, :boolean
    remove_column :estimates, :detail2, :integer
    remove_column :estimates, :genre_id2, :integer
    remove_column :estimates, :product2, :string
    remove_column :estimates, :model2, :string
    remove_column :estimates, :amount2, :integer
    remove_column :estimates, :unit_price2, :integer
    remove_column :estimates, :recruit2, :boolean
    remove_column :estimates, :detail3, :integer
    remove_column :estimates, :genre_id3, :integer
    remove_column :estimates, :product3, :string
    remove_column :estimates, :model3, :string
    remove_column :estimates, :amount3, :integer
    remove_column :estimates, :unit_price3, :integer
    remove_column :estimates, :recruit3, :boolean
    remove_column :estimates, :detail4, :integer
    remove_column :estimates, :genre_id4, :integer
    remove_column :estimates, :product4, :string
    remove_column :estimates, :model4, :string
    remove_column :estimates, :amount4, :integer
    remove_column :estimates, :unit_price4, :integer
    remove_column :estimates, :recruit4, :boolean
    remove_column :estimates, :detail5, :integer
    remove_column :estimates, :genre_id5, :integer
    remove_column :estimates, :product5, :string
    remove_column :estimates, :model5, :string
    remove_column :estimates, :amount5, :integer
    remove_column :estimates, :unit_price5, :integer
    remove_column :estimates, :recruit5, :boolean
    remove_column :estimates, :detail6, :integer
    remove_column :estimates, :genre_id6, :integer
    remove_column :estimates, :product6, :string
    remove_column :estimates, :model6, :string
    remove_column :estimates, :amount6, :integer
    remove_column :estimates, :unit_price6, :integer
    remove_column :estimates, :recruit6, :boolean
    remove_column :estimates, :detail7, :integer
    remove_column :estimates, :genre_id7, :integer
    remove_column :estimates, :product7, :string
    remove_column :estimates, :model7, :string
    remove_column :estimates, :amount7, :integer
    remove_column :estimates, :unit_price7, :integer
    remove_column :estimates, :recruit7, :boolean
    remove_column :estimates, :detail8, :integer
    remove_column :estimates, :genre_id8, :integer
    remove_column :estimates, :product8, :string
    remove_column :estimates, :model8, :string
    remove_column :estimates, :amount8, :integer
    remove_column :estimates, :unit_price8, :integer
    remove_column :estimates, :recruit8, :boolean
    remove_column :estimates, :detail9, :integer
    remove_column :estimates, :genre_id9, :integer
    remove_column :estimates, :product9, :string
    remove_column :estimates, :model9, :string
    remove_column :estimates, :amount9, :integer
    remove_column :estimates, :unit_price9, :integer
    remove_column :estimates, :recruit9, :boolean
    remove_column :estimates, :detail10, :integer
    remove_column :estimates, :genre_id10, :integer
    remove_column :estimates, :product10, :string
    remove_column :estimates, :model10, :string
    remove_column :estimates, :amount10, :integer
    remove_column :estimates, :unit_price10, :integer
    remove_column :estimates, :recruit10, :boolean
    remove_column :estimates, :detail11, :integer
    remove_column :estimates, :genre_id11, :integer
    remove_column :estimates, :product11, :string
    remove_column :estimates, :model11, :string
    remove_column :estimates, :amount11, :integer
    remove_column :estimates, :unit_price11, :integer
    remove_column :estimates, :recruit11, :boolean
    remove_column :estimates, :detail12, :integer
    remove_column :estimates, :genre_id12, :integer
    remove_column :estimates, :product12, :string
    remove_column :estimates, :model12, :string
    remove_column :estimates, :amount12, :integer
    remove_column :estimates, :unit_price12, :integer
    remove_column :estimates, :recruit12, :boolean
    remove_column :estimates, :detail13, :integer
    remove_column :estimates, :genre_id13, :integer
    remove_column :estimates, :product13, :string
    remove_column :estimates, :model13, :string
    remove_column :estimates, :amount13, :integer
    remove_column :estimates, :unit_price13, :integer
    remove_column :estimates, :recruit13, :boolean
    remove_column :estimates, :detail14, :integer
    remove_column :estimates, :genre_id14, :integer
    remove_column :estimates, :product14, :string
    remove_column :estimates, :model14, :string
    remove_column :estimates, :amount14, :integer
    remove_column :estimates, :unit_price14, :integer
    remove_column :estimates, :recruit14, :boolean
    remove_column :estimates, :detail15, :integer
    remove_column :estimates, :genre_id15, :integer
    remove_column :estimates, :product15, :string
    remove_column :estimates, :model15, :string
    remove_column :estimates, :amount15, :integer
    remove_column :estimates, :unit_price15, :integer
    remove_column :estimates, :recruit15, :boolean
    remove_column :estimates, :detail16, :integer
    remove_column :estimates, :genre_id16, :integer
    remove_column :estimates, :product16, :string
    remove_column :estimates, :model16, :string
    remove_column :estimates, :amount16, :integer
    remove_column :estimates, :unit_price16, :integer
    remove_column :estimates, :recruit16, :boolean
    remove_column :estimates, :detail17, :integer
    remove_column :estimates, :genre_id17, :integer
    remove_column :estimates, :product17, :string
    remove_column :estimates, :model17, :string
    remove_column :estimates, :amount17, :integer
    remove_column :estimates, :unit_price17, :integer
    remove_column :estimates, :recruit17, :boolean
    remove_column :estimates, :detail18, :integer
    remove_column :estimates, :genre_id18, :integer
    remove_column :estimates, :product18, :string
    remove_column :estimates, :model18, :string
    remove_column :estimates, :amount18, :integer
    remove_column :estimates, :unit_price18, :integer
    remove_column :estimates, :recruit18, :boolean
    remove_column :estimates, :detail19, :integer
    remove_column :estimates, :genre_id19, :integer
    remove_column :estimates, :product19, :string
    remove_column :estimates, :model19, :string
    remove_column :estimates, :amount19, :integer
    remove_column :estimates, :unit_price19, :integer
    remove_column :estimates, :recruit19, :boolean
    remove_column :estimates, :detail20, :integer
    remove_column :estimates, :genre_id20, :integer
    remove_column :estimates, :product20, :string
    remove_column :estimates, :model20, :string
    remove_column :estimates, :amount20, :integer
    remove_column :estimates, :unit_price20, :integer
    remove_column :estimates, :recruit20, :boolean
  end
end
